### PR TITLE
Fix handling errors

### PR DESCRIPTION
**Pull request by abhinavk99**
In my last PR, I forgot to reject errors in the `get` methods that I caught when calling the `request` method, so I'm fixing that now. Sorry about the mistake.

### CODE REVIEW

**Comment by ickerio** [comment]
Thanks, do you want to be made a contributor to the repo?

**Comment by abhinavk99** [comment]
Yeah that would be great.

**Comment by abhinavk99** [comment]
@ickerio Sorry to push you on this, but have you gotten around to inviting me as a contributor?

**Comment by ickerio** [comment]
Done 👍

**Pull request merged**
